package Beans;

import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import javax.enterprise.context.ApplicationScoped;

import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.sql.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@ApplicationScoped
public class DataBaseService {

    private static final String URL =
            "jdbc:hsqldb:file:./data/lab3db";
    private static final String USER = "sa";
    private static final String PASS = "";
    private final YandexDiskXlsxAppender ya;


    public DataBaseService() {
        init();
        this.ya = new YandexDiskXlsxAppender(readYaDiskToken(), "/weblab3/history.xlsx");
    }

    private void init() {
        try (Connection c = DriverManager.getConnection(URL, USER, PASS);
             Statement st = c.createStatement()) {

            // ВАЖНО: DECIMAL вместо DOUBLE для точности
            st.executeUpdate("""
                CREATE TABLE IF NOT EXISTS results (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    x DECIMAL(40, 20) NOT NULL,
                    y DECIMAL(40, 20) NOT NULL,
                    r DECIMAL(40, 20) NOT NULL,
                    hit BOOLEAN NOT NULL,
                    timestamp TIMESTAMP NOT NULL
                )
            """);



        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void saveResult(BigDecimal x, BigDecimal y, BigDecimal r, Boolean hit) {
        String sql = "INSERT INTO results (x,y,r,hit,timestamp) VALUES (?,?,?,?,?)";
        Timestamp ts = new Timestamp(new Date().getTime());

        try (Connection c = DriverManager.getConnection(URL, USER, PASS);
             PreparedStatement ps = c.prepareStatement(sql)) {

            ps.setBigDecimal(1, x);
            ps.setBigDecimal(2, y);
            ps.setBigDecimal(3, r);
            ps.setBoolean(4, hit != null && hit);
            ps.setTimestamp(5, ts);
            ps.executeUpdate();

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        try {
            ya.appendRow(java.util.List.of(
                    x.toPlainString(),
                    y.toPlainString(),
                    r.toPlainString(),
                    String.valueOf(hit != null && hit),
                    ts.toString()
            ));
        } catch (Exception e) {
            System.err.println("Yandex Disk append failed: " + e.getMessage());
        }
    }


    public List<ResultPoint> getAllResults() {
        List<ResultPoint> list = new ArrayList<>();
        String sql =
                "SELECT x,y,r,hit,timestamp FROM results ORDER BY timestamp DESC";

        try (Connection c = DriverManager.getConnection(URL, USER, PASS);
             PreparedStatement ps = c.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                list.add(new ResultPoint(
                        rs.getBigDecimal("x"),
                        rs.getBigDecimal("y"),
                        rs.getBigDecimal("r"),
                        rs.getBoolean("hit"),
                        rs.getTimestamp("timestamp")
                ));
            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        return list;
    }

    public List<ResultPoint> getResultsByRadius(BigDecimal radius) {
        List<ResultPoint> list = new ArrayList<>();
        String sql =
                "SELECT x,y,r,hit,timestamp FROM results WHERE r=? ORDER BY timestamp DESC";

        try (Connection c = DriverManager.getConnection(URL, USER, PASS);
             PreparedStatement ps = c.prepareStatement(sql)) {

            ps.setBigDecimal(1, radius);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    list.add(new ResultPoint(
                            rs.getBigDecimal("x"),
                            rs.getBigDecimal("y"),
                            rs.getBigDecimal("r"),
                            rs.getBoolean("hit"),
                            rs.getTimestamp("timestamp")
                    ));
                }
            }

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        return list;
    }

    public int getResultsCount() {
        try (Connection c = DriverManager.getConnection(URL, USER, PASS);
             PreparedStatement ps = c.prepareStatement("SELECT COUNT(*) FROM results");
             ResultSet rs = ps.executeQuery()) {

            rs.next();
            return rs.getInt(1);

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void clearResults() {
        try (Connection c = DriverManager.getConnection(URL, USER, PASS);
             Statement st = c.createStatement()) {

            st.executeUpdate("DELETE FROM results");

        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        try {
            ya.clear();
        } catch (Exception e) {
            System.err.println("Yandex Disk clear failed: " + e.getMessage());
        }
    }


    private String readYaDiskToken() {
        try {
            java.nio.file.Path p = java.nio.file.Paths.get(".weblab3", "yadisk_token.txt");
            return java.nio.file.Files.readString(p).trim();
        } catch (Exception e) {
            throw new RuntimeException("Cannot read Yandex Disk token", e);
        }
    }

    public void syncHistoryToYaDisk() {
        List<ResultPoint> rows = getAllResults();

        try {
            Workbook wb = new XSSFWorkbook();
            Sheet sh = wb.createSheet("history");

            Row header = sh.createRow(0);
            header.createCell(0).setCellValue("x");
            header.createCell(1).setCellValue("y");
            header.createCell(2).setCellValue("r");
            header.createCell(3).setCellValue("hit");
            header.createCell(4).setCellValue("timestamp");

            int i = 1;
            for (ResultPoint rp : rows) {
                Row row = sh.createRow(i++);
                row.createCell(0).setCellValue(rp.getX().toPlainString());
                row.createCell(1).setCellValue(rp.getY().toPlainString());
                row.createCell(2).setCellValue(rp.getR().toPlainString());
                row.createCell(3).setCellValue(String.valueOf(rp.getHit()));
                row.createCell(4).setCellValue(String.valueOf(rp.getTimestamp()));
            }

            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            wb.write(bos);
            wb.close();

            ya.overwrite(bos.toByteArray());
        } catch (Exception e) {
            throw new RuntimeException("Не удалось синхронизировать файл на Яндекс.Диске: " + e.getMessage(), e);
        }
    }


}
